[build]
builder = "NIXPACKS"
buildCommand = "echo 'Cache bust v6' && npx prisma generate && ./node_modules/.bin/tsc -p tsconfig.build.json 2>&1 || true"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node dist/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
